version: '3.8'

services:
  web:
    build: .
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: partsdb
      POSTGRES_USER: partsuser
      POSTGRES_PASSWORD: partspass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
